-- Estrutura complementar para estoque por cliente, portal autorizado,
-- OTP por SMS e fila futura de envio de relatorios por WhatsApp.

alter table public.clientes
  add column if not exists quantidade_produtos_contratados numeric not null default 0,
  add column if not exists portal_habilitado boolean not null default false;

create table if not exists public.cliente_estoque (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  produto_id bigint not null references public.produtos(id) on delete cascade,
  quantidade numeric not null default 0,
  estoque_minimo numeric not null default 0,
  atualizado_em timestamptz not null default now(),
  unique (cliente_id, produto_id)
);

create table if not exists public.ordem_servico_produtos (
  id bigint generated by default as identity primary key,
  ordem_servico_id bigint not null references public.ordens_servico(id) on delete cascade,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  produto_id bigint references public.produtos(id) on delete set null,
  produto_nome text not null,
  quantidade numeric not null default 0,
  unidade text,
  criado_em timestamptz not null default now()
);

create table if not exists public.estoque_movimentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  produto_id bigint references public.produtos(id) on delete set null,
  ordem_servico_id bigint references public.ordens_servico(id) on delete set null,
  quantidade numeric not null,
  tipo text not null check (tipo in ('entrada', 'uso', 'ajuste')),
  criado_em timestamptz not null default now()
);

create table if not exists public.cliente_otp_codigos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  telefone text not null,
  codigo_hash text not null,
  expira_em timestamptz not null,
  consumido_em timestamptz,
  tentativas integer not null default 0,
  criado_em timestamptz not null default now()
);

create table if not exists public.relatorio_envio_fila (
  id bigint generated by default as identity primary key,
  ordem_servico_id bigint not null references public.ordens_servico(id) on delete cascade,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  canal text not null default 'whatsapp',
  destinatario text not null,
  relatorio_url text not null,
  status text not null default 'pending',
  payload jsonb,
  erro text,
  criado_em timestamptz not null default now(),
  enviado_em timestamptz
);

create index if not exists cliente_estoque_cliente_idx on public.cliente_estoque(cliente_id);
create index if not exists estoque_movimentos_cliente_idx on public.estoque_movimentos(cliente_id);
create index if not exists ordem_servico_produtos_ordem_idx on public.ordem_servico_produtos(ordem_servico_id);
create index if not exists cliente_otp_codigos_telefone_idx on public.cliente_otp_codigos(telefone);
